inherit_from: .rubocop_todo.yml

StringLiterals:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashSyntax:
  Enabled: false